apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth

resources:
- github.com/davidspek/manifests/common/dex/overlays/istio?ref=dex-remove-base

patchesStrategicMerge:
- configmap-patch.yaml

images:
- name: quay.io/dexidp/dex
  newName: quay.io/dexidp/dex
  newTag: v2.28.1
